// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI agent that recommends crops based on soil analysis and weather conditions.
 *
 * - recommendCrops - A function that handles the crop recommendation process.
 * - CropRecommendationInput - The input type for the recommendCrops function.
 * - CropRecommendationOutput - The return type for the recommendCrops function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CropRecommendationInputSchema = z.object({
  soilType: z
    .string()
    .describe('The type of soil available, examples include: black soil, red soil, alluvial soil, laterite soil.'),
  historicalWeatherData: z
    .string()
    .describe('Historical weather data for the region, including average rainfall, temperature, and humidity.'),
  marketDemand: z
    .string()
    .describe('Information on the current market demand for various crops in the region.'),
});
export type CropRecommendationInput = z.infer<typeof CropRecommendationInputSchema>;

const CropRecommendationOutputSchema = z.object({
  recommendedCrops: z
    .array(z.string())
    .describe('An array of recommended crops to plant based on the input data.'),
  reasoning: z
    .string()
    .describe('Explanation of why these crops are recommended based on soil, weather, and market conditions.'),
});
export type CropRecommendationOutput = z.infer<typeof CropRecommendationOutputSchema>;

export async function recommendCrops(input: CropRecommendationInput): Promise<CropRecommendationOutput> {
  return recommendCropsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'cropRecommendationPrompt',
  input: {schema: CropRecommendationInputSchema},
  output: {schema: CropRecommendationOutputSchema},
  prompt: `You are an expert agricultural advisor for farmers in India. You are provided with the soil type, historical weather data, and market demand for various crops in the region.

  Based on this information, provide a list of recommended crops to plant and a detailed explanation of why these crops are recommended.

  Soil Type: {{{soilType}}}
  Historical Weather Data: {{{historicalWeatherData}}}
  Market Demand: {{{marketDemand}}}
  `,
});

const recommendCropsFlow = ai.defineFlow(
  {
    name: 'recommendCropsFlow',
    inputSchema: CropRecommendationInputSchema,
    outputSchema: CropRecommendationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
